### ISSUE TITLE
[osx] error: default initialization of an object of const type

### ISSUE THREAD

**Issue by ras0219-msft** [GoogleCloudPlatform/google-cloud-cpp#1593]
### Does this issue affect the `google-cloud-cpp` project?

Yes

### What version of `google-cloud-cpp` are you using?

a0f27355af654605b321e764a7dd9464c54340a3

### What compiler and version are you using?

```
$ cc -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
```

### What operating system and version are you using?

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
```

### What were you trying to do?

Compile

### What was the compilation error?

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971 -I. -isystem /Users/ras0219/vcpkg/installed/x64-osx/include -fPIC   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -Wall -Werror -std=gnu++11 -MD -MT google/cloud/CMakeFiles/future_generic_test.dir/future_generic_test.cc.o -MF google/cloud/CMakeFiles/future_generic_test.dir/future_generic_test.cc.o.d -o google/cloud/CMakeFiles/future_generic_test.dir/future_generic_test.cc.o -c /Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971/google/cloud/future_generic_test.cc
/Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971/google/cloud/future_generic_test.cc:462:21: error: default initialization of an object of const type 'const future<int>' without a user-provided default constructor
  future<int> const f;
                    ^
/Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971/google/cloud/future_generic_test.cc:462:22: note: add an explicit initializer to initialize 'f'
  future<int> const f;
                     ^
                     {}
1 error generated.
```

**Comment by coryan** [comment]
This looks like a compiler bug, the code says:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/0c254c902907fa49bd89f22aa23e7ef9f3e67fdf/google/cloud/future_generic.h#L40

And it compiles on macOS with clang-902.0.39.2:

https://travis-ci.org/coryan/google-cloud-cpp/jobs/463987971

Testing with Xcode 7.3 right now (the oldest one I have access to), so we can reproduce it before trying a workaround.

**Comment by coryan** [comment]
I have just sent a PR for review.  @ras0219-msft how important is the Xcode 7.x series?  The compiler does not seem to have full C++11 support, so unless there is a large constituency using the that version we would be more inclined to recommend that folks upgrade to newer versions of Xcode.
