### PR TITLE
Fix build with Xcode 7.3.

### LINKED ISSUE #1593: [osx] error: default initialization of an object of const type
### Does this issue affect the `google-cloud-cpp` project?

Yes

### What version of `google-cloud-cpp` are you using?

a0f27355af654605b321e764a7dd9464c54340a3

### What compiler and version are you using?

```
$ cc -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
```

### What operating system and version are you using?

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
```

### What were you trying to do?

Compile

### What was the compilation error?

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971 -I. -isystem /Users/ras0219/vcpkg/installed/x64-osx/include -fPIC   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -Wall -Werror -std=gnu++11 -MD -MT google/cloud/CMakeFiles/future_generic_test.dir/future_generic_test.cc.o -MF google/cloud/CMakeFiles/future_generic_test.dir/future_generic_test.cc.o.d -o google/cloud/CMakeFiles/future_generic_test.dir/future_generic_test.cc.o -c /Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971/google/cloud/future_generic_test.cc
/Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971/google/cloud/future_generic_test.cc:462:21: error: default initialization of an object of const type 'const future<int>' without a user-provided default constructor
  future<int> const f;
                    ^
/Users/ras0219/vcpkg/buildtrees/google-cloud-cpp/src/64c54340a3-41a12c0971/google/cloud/future_generic_test.cc:462:22: note: add an explicit initializer to initialize 'f'
  future<int> const f;
                     ^
                     {}
1 error generated.
```

### PR DESCRIPTION
**Pull request by coryan**
This fixes #1593. It worksaround compiler bugs in Xcode 7.x.  I have
filed a separate bug (#1602) to decide if we want to drop support for
the compiler in the future.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1603)

### CODE REVIEW

File: google/cloud/future_generic.h [hunk 1]
```diff
@@ -37,7 +37,9 @@ class future final : private internal::future_base<T> {
   using shared_state_type =
       typename internal::future_base<T>::shared_state_type;
 
-  future() noexcept = default;
+  // workaround Apple Clang-7xx series bug, if we use `= default` here the
```
Comment (mbrukman) [inline google/cloud/future_generic.h]: s/here the/here, the/

File: google/cloud/future_generic.h [hunk 2]
```diff
@@ -37,7 +37,9 @@ class future final : private internal::future_base<T> {
...
+  // compiler believes there is no default constructor defined :shrug:
```
Comment (mbrukman) [inline google/cloud/future_generic.h]: s/defined/defined./ :smile:
